source 'https://rubygems.org'

gemspec
gem 'rspec'
gem 'rails', '~> 3.2.12'
gem 'simplecov'
gem 'ruby_gntp'
gem 'growl'
gem 'spork'
gem 'guard'
gem 'guard-test'
gem 'guard-rspec'
gem "mocha", '0.12.1', :require => false
gem 'fl-rocco'
gem 'redcarpet', '~> 1.17'
# gem 'markdown'
gem 'maruku'
gem 'faraday'
gem 'cucumber'
gem 'aruba'
gem 'sqlite3'